google/closure-compiler-npm

lib/node/closure-compiler.js

Fix extraCommandArgs not being copied.
Fixes https://github.com/ChadKillingsworth/closure-compiler-npm/issues/18

Fix extraCommandArgs not being copied

---

README.md
lib/grunt/index.js
lib/gulp/index.js
test/gulp.js

Fixes #16 
@Dominator008 Have time to look at this?

Add a .src method to the gulp plugin to support usage without gulp.src

---

lib/gulp/index.js
test/gulp.js

Fixes #24 
The `close` event for the spawned process can occur before the `end` events for standard out and error streams - thus truncating any messages being written. Wait for the `end` of both streams AND the `close` event on the spawned process before triggering the after compilation logic.

Wait for the 'end' event on stdout/err before writing out the messages

---

lib/gulp/index.js

Specific to the gulp plugin: log the error data before emitting the error event so that they are seen before the process exits.

Write out standard error before exiting on errors

---

lib/gulp/concat-to-json.js
lib/gulp/index.js
test/gulp.js

While testing google/closure-compiler#1971, I found a bug where input sourcemaps were being passed into the compiler on a misnamed property. Thus the plugin is currently not providing input sourcemaps at all.
This fixes the issue.

Fix a bug which was passing input source maps in on a misnamed property

---

build_compiler.js

When testing changes locally, we don't need to download the jar every test run. This limits the download to cases where the jar is out of date or does not exist.

Only download the compiler.jar if it doesn't already exist

---

lib/gulp/index.js
package.json

Remove manual source map composition as the compiler now does that natively

---

.travis.yml

Node 5 is no longer supported. Switch to testing against Node 7.

Replace travis tests with Node 7

---

lib/grunt/index.js
lib/grunt/vinyl-stream.js
lib/gulp/index.js
lib/gulp/json-to-vinyl.js
package.json

[vinyl-fs]() and [gulp-util]() end up importing a huge dependency tree.
vinyl-fs was used by the grunt plugin, but only a very small feature set was needed. Replaced with a custom written class.
gulp-util is used for custom error classes and logging. If it exists (because gulp is present), use that. Otherwise use the provided fallbacks.
Alleviates #47 and #41

Reduce Dependencies

---

lib/node/closure-compiler.js

This PR has come out of the suggestion to investigate nailgun https://github.com/google/closure-compiler/issues/2186
fast-closure-compiler passes the arguments to a python script which in turn passes it to the nailgun server. `-jar` gets passed all the way down to the closure compiler, resulting in this error:
```
"-jar" is not a valid option
```
Therefore, I suggest to not add `-jar` if `JAR_PATH` is falsy. Library consumers like me then have a switch to extend this libraries' functionality to work with nailgun.

Do not add --jar if JAR_PATH is empty

---

.travis.yml
package.json

Support all maintained versions.
https://github.com/google/closure-compiler-npm/commit/2cd5e0a8d10e7a243229e0928c55227531dc95df dropped v4, but the comment
> Drop node 4 support as it no longer is maintained.
is wrong. v4 is maintained by April 2018 as LTS.
https://github.com/nodejs/LTS
Also test in v8 instead of v7.

Support Node v4, v6 and v8

---

cli.js
package.json

This adds a binary to the distribution named `google-closure-compiler`. It's essentially a very thin wrapper around `java -jar path/to/google-closure-compiler/compiler.jar`. This means folks can access it as a cli w/o having to dig up where it's installed.
It also means that it's usable via npx. With the patch applied and published, this becomes possible:
```
$ npx google-closure-compiler …
```
Which can be used if you have it installed as a dev dep (in which case it'll be nearly instant) or even if you don't have it installed (which takes ~3s with a warm cache).
I should add, in the PR I left the bin name the same as the package, but there's no reason it couldn't be something more concise, like just `closure`.

Add bin wrapper for easier cli use

---

index.js

Saves memory and parse time - the JS version is very large

Switch the main file to use getters to defer loading the JS version

---

README.md

There is now a Rollup plugin for Closure Compiler leveraging `closure-compiler-npm`. Thought it might make sense to list it here as well.

Update README.md with Rollup Plugin Reference

---

package.json

Gulp is directly required by the grunt plugin currently. We should probably change that at some point. But for now gulp needs to be a dependency of the project.

Move gulp back to a dependency as it is required for grunt

---

.gitignore
README.md
build_compiler.js
cli.js
deployments.md
docs/grunt.md
docs/gulp.md
lib/grunt/index.js
lib/gulp/index.js
lib/node/closure-compiler.js
lib/utils.js
package.json
test/cli.js
test/compiler.js
test/grunt.js
test/gulp.js
test/node.js
version-match.js
yarn.lock

Adds the new graal native packages as optional dependencies. They will be installed if their OS and architecture restrictions are met.
Updates the grunt and gulp plugins to support a `platform` flag to switch between each version of the compiler. The flag may be an array in preference order where the first supported platform will be used.
If the java platform is not the last platform listed, support for java will be detected by the presence of the `JAVA_HOME` environment variable.
Currently, `java` remains the default platform but the native versions may become default when available by a future release.

Support the native graal packages

---

lib/grunt/index.js
package.json
test/grunt.js

Gulp dependencies have security vulnerabilities so we need to not directly depend on them

Remove gulp as a direct dependency of the grunt plugin

---

cli.js
lib/gulp/index.js
lib/logger.js
lib/node/closure-compiler-js.js
lib/utils.js
test/gulp.js

Cli logging for the JavaScript platform is broken. This moves the logger utility from the js repo over and uses it for the cli as well as the gulp plugin.

Move over and use the cli logger from the closure-compiler-js repo

---

build_compiler.js
deployments.md

Without the `--fail` flag, curl has an exit code of 0 even if it receives an HTTP Status code that indicates an error.

Fail the build script if curl receives a non-success HTTP status code

---

cli.js
test/cli.js
test/fixtures/extern.js
test/gulp.js

Now that https://github.com/google/closure-compiler/pull/3036 is in a release, the cli script can be significantly simplified.
Rather than the cli script reading the input files and passing them into the compiler, just use the `--js` and `--extern` flags and let them be loaded from the filesystem directly.
Also adds support to the cli to create the output files and associated directories when either the `--js_output_file` or `--chunk` flags are specified. Creates source map files on disk when the `--create_source_map` flag is used.

Simplify the cli script now that the GWT version has filesystem support

---

test/gulp.js

It shows deprecation warnings in Node v10.

Replace deprecated new Buffer() with Buffer.from()

---

.travis.yml
build-scripts/graal.js
build-scripts/lerna-publish.js
build-scripts/npm-client.js
deployments.md

Now that the mono repo is fully merged, clean up some of the scripts.
1. Remove the ability to build Graal from source. We didn't need it for the release and hopefully we won't ever go back to that.
2. Rework the logging during npm publication so that all messages from a particular publish job write to the file sequentially.
3. Add more deployment instructions.

Cleanup Build Scripts

---

build-scripts/build.sh
build-scripts/test.sh

If any single command in either the build or test script fails, the entire script should have a failing exit status.

Fail the build scripts if any single command fails

---

build-scripts/reflection-config.json

Fixes #109 
Additional reflection was needed to support conformance configs under Graal.

Enable the reflection needed for conformance configs to operate in Graal

---

.travis.yml
build-scripts/create-nightly-version.js
build-scripts/lerna-publish.js
package.json
yarn.lock

We publish nightly snapshot releases to maven, but we haven't done the same with npm. This forces most developers to wait for the next release to adopt changes - or possibly even help test changes.
This PR utilizes the nightly travis cron job to publish a snapshot build of the compiler to npm on all platforms. The packages are published with a "nightly" tag so they won't be auto-installed by users unless they opt-in to a specific version number or install with `npm install google-closure-compiler@nightly`.

Publish a nightly releases of the compiler to npm

---

packages/google-closure-compiler/lib/gulp/index.js
packages/google-closure-compiler/test/gulp.js

The gulp plugin had a promise without a catch clause. Apparently it was possible to trigger a rejection on that promise (though I've never really seen it).
Add a catch clause and report the error with a stack trace.
Fixes #122

Add a catch to the gulp plugin promise to report unknown errors

---

build-scripts/create-nightly-version.js

Travis checks out the repo as a disconnected head, but Lerna will only create a new version on a branch.
So create and checkout a new branch before continuing with the nightly release.

Create a branch for the nightly release.

---

.travis.yml
build-scripts/create-nightly-version.js

The version command of lerna requires a clean working tree. Add the known modified files of the nightly build to a commit before attempting to create the version.

During the nightly release, add the modified files to a git commit

---

build-scripts/clean.sh
package.json

Helps with local debugging. Run `yarn clean` before `yarn build` to ensure that new compiler artifacts are used.

Add a clean build script to facilitate removing build artifacts

---

packages/google-closure-compiler/lib/gulp/index.js

Allow time to detect that the external process successfully started.
Better detects launch errors (such as when invalid flags are passed) before attempting to write to stdin.
Hopefully, this addresses #130

For gulp, delay writing to stdin

---

packages/google-closure-compiler/lib/gulp/index.js

This is another attempt at fixing #130.

Treat errors writing to stdin of the subprocess like an error message

---

.gitignore
.travis.yml
README.md
appveyor.yml
build-scripts/add-os-restrictions.js
build-scripts/build_compiler.js
build-scripts/clean.sh
build-scripts/graal-env.js
build-scripts/graal.js
build-scripts/npm-client.js
build-scripts/run-command.js
package.json
packages/google-closure-compiler-windows/build-image.js
packages/google-closure-compiler-windows/index.js
packages/google-closure-compiler-windows/package.json
packages/google-closure-compiler-windows/readme.md
packages/google-closure-compiler-windows/test.js
packages/google-closure-compiler/README.md
packages/google-closure-compiler/lib/node/closure-compiler.js
packages/google-closure-compiler/lib/utils.js
packages/google-closure-compiler/package.json
packages/google-closure-compiler/test/cli.js
packages/google-closure-compiler/test/gulp.js
packages/google-closure-compiler/test/node.js
yarn.lock

Creates a native image package for windows
Moves the minimum node version to 8 and add support for node 12.
I was unable to get travis to build the image, but Appveyor was successful and is also free for open source projects: https://ci.appveyor.com/project/ChadKillingsworth/closure-compiler-npm
I'll need to work with someone who has owner access to this repo to properly integrate Appveyor into builds. Publishing will have to be added after this is merged.

Support native images on windows

---

package.json
packages/google-closure-compiler/package.json
yarn.lock

Specifies more permissive version ranges. The yarn.lock file keeps builds consistent.

Update more of the dependencies

---

appveyor.yml

Appveyor builds are giving a generic error trying to install yarn. Update the build command to address this.

Fix windows builds on Appveyor

---

packages/google-closure-compiler/lib/gulp/index.js
packages/google-closure-compiler/test/gulp.js

Special case the exceptions thrown for invalid flags and values, but pass the full stack trace for any other error. Will significantly improve debugging of the JS version.

Don't swallow unexpected exceptions from the JS version in the gulp plugin

---

packages/google-closure-compiler/cli.js

Do not blindly create directories like 'C:\' in mkDirByPathSync, but check if the directory exists first. #161

Do not blindly create directories like 'C:\' in mkDirByPathSync

---

packages/google-closure-compiler/docs/grunt.md
packages/google-closure-compiler/lib/grunt/index.js

Hello!
We use compilator with grunt config like:
```
files: [{
expand: true,
src: [
'built/bin/**/*.js',
'built/bootstrap/**/*.js',
'built/cron/**/*.js',
'built/lib/**/*.js',
'built/models/**/*.js',
'built/rest/**/*.js',
'built/routes/**/*.js',
'built/controllers/**/main.js',
'built/controllers/**/master.js',
'built/controllers-modules/**/*.js'
],
dest: '.builttemp',
cwd: '.'
}],
```
Grunt plugin by default creates ton of parallel compiler processes and jenkins crashes.
Made useful option to restrict number of parallel compiler processes. Default for compiling all files at once not changed.

Grunt option compile_in_batches to optionally compile not all files in parallel

---

packages/google-closure-compiler-js/test.js

Right now this test is giving an incorrect error at best, and a misleading error at worst. I encountered this trying to debug the closure-compiler CI, and found that there was a real error loading this package that wasn't getting logged. Adding the `console.log` here ensures the error is well formatted with a stack trace and everything.

Add better logging to js testing

---

packages/google-closure-compiler/docs/grunt.md
packages/google-closure-compiler/lib/grunt/index.js

Optimized parallelization algorithm. Now old batch can't wait for its last promise to start new batch. Here number of parallel (compile_in_batch number) consumers which grab promises by one and process sequentially. No bottleneck.

rework(grunt): optimized algorithm for compile_in_batches parameter

---

packages/google-closure-compiler-java/package.json
packages/google-closure-compiler-linux/package.json
packages/google-closure-compiler-osx/package.json
packages/google-closure-compiler-windows/package.json

Fixes the issue in #168 with the binary packages (`google-closure-compiler-osx`, etc) not being unplugged in Yarn's plug-n-play. I set the preferUnplugged in `package.json`s of each affected package.
Test
```
mkdir test-unplugged
cd test-unplugged
yarn set version berry
yarn init
yarn add /Users/seamusleahy/projects/closure-compiler-npm/packages/google-closure-compiler-osx
cd .yarn/unplugged
ls
```
Expect to see a `google-closure-compiler-osx-<source>-<hash>` folder with all the contents of the package. If it doesn't work, then it will not have a folder inside of `.yarn/unplugged`.

Force binary packages to be unplugged when using Yarn's pnp

---

.github/workflows/build.yml

Add a build step to explicitly mark the downloaded artifacts as executable
Fixes #188

Mark the downloaded binaries as executable

---

packages/google-closure-compiler/cli.js

Currently --platform is read as a single string if present and the value defaults to a preference ordered list if not specified. After this change it will be a comma separated list when present. This also means that invalid platform specifiers will throw an error.
Closes https://github.com/google/closure-compiler-npm/issues/197

Treat --platform flag as a preferences ordered list in cli.js

---

build-scripts/reflection-config.json

The conformance rule has been deleted, and hopefully this will fix
the broken build at
https://github.com/google/closure-compiler/runs/2579755422.

Delete BanExpose entry in reflection config

---

packages/google-closure-compiler/test/gulp.js

The compiler's default `--language_out` has changed from `ECMASCRIPT5` to
`ECMASTRICT_NEXT`. This broke tests that assumed the old default value.

Explicitly specify ES5 output for gulp.js tests

---

.github/workflows/build.yml

Should fix a CI error (https://github.com/google/closure-compiler-npm/actions/runs/1761399002) caused by https://github.com/google/closure-compiler/commit/c282b0c5280afff1ace3497fa0d5da5f3e7f9dca.

Bump Bazel version to 4.2.2

---

packages/google-closure-compiler/lib/grunt/vinyl-stream.js

While working on https://github.com/google/closure-compiler-npm/pull/226, the Grunt plugin started failing on newer versions of Node. I was able to replicate this same failure locally.
The grunt streaming code was written long ago. When I reviewed that code, I found several oddities contributing to this failure.
- Remove the recursive call. The client will re-call read again for us.
- Push "null" instead of synthetically ending the stream
- Simplify into a single function call
The tests all pass locally for me now on Node 16 (were failing before). I don't have any projects that use Grunt anymore so we'll have to depend on community feedback to know for sure that this continues to work.
It's possible that this will address the concerns in …

Update the VinylStream class used by the Grunt plugin

---

.github/workflows/build.yml
build-scripts/graal-env.js
build-scripts/graal.js

Followup to https://github.com/google/closure-compiler-npm/pull/220
See if the new GRAAL version and JDK versions will produce smaller binaries.

Upgrade GRAAL version and JDK build

---

.github/workflows/build.yml

This PR proposes upx compression of the compiler for Linux, due to the reasons reported at #186. The building workflows are [tested in my fork](https://github.com/itchyny/closure-compiler-npm/actions/runs/2063794971). Compared to the [latest build log](https://github.com/google/closure-compiler-npm/actions/runs/2058334239), the compiler size has been compressed from 307MiB to 86MiB.
Resolves #186.

Install upx in CI and minify the compiler for Linux

---

packages/google-closure-compiler/lib/utils.js

google-closure-compiler tries to use the native Linux build on every architecture, including ones for which there is no native build yet (e.g., arm64). We need to fall back to Java until a native build is available for the arm64 architecture.

Only use native Linux compiler on x86 platforms

---

.github/workflows/build.yml

Updates build steps to test on the 3 main versions of Node currently supported. Also explicitly declare the version of Node used for publication to NPM.

Update Node versions used in GitHub Actions

---

.github/workflows/build.yml
build-scripts/build_compiler.js

Fixes #242 
- Example build where it chooses Bazel 4.2.2: https://github.com/google/closure-compiler-npm/runs/6707265420
- Example build where it chooses Bazel 5.1.1: https://github.com/google/closure-compiler-npm/runs/6707403758

Migrate to Bazelisk (fixes CI failure with HEAD compiler)

---

packages/google-closure-compiler/cli.js

removed mkDirByPathSync (as it was not being used for anything)
besides node have this built in now.

removed dead code

---

.github/workflows/release.yml
.gitignore
build-scripts/publish.js

Updating npm publication to ensure that the correct registry is used.
Also update the release workflow to indicate that it needs access to push commits and tags back to the repository.

Use a project local .npmrc file for publication

---

packages/google-closure-compiler/test/cli.js
packages/google-closure-compiler/test/grunt.js
packages/google-closure-compiler/test/gulp.js

Supports testing the npm package in the main compiler CI pipeline

Add a --java-only flag to allow only the java tests to be run

---

.github/workflows/build.yml
.github/workflows/release.yml

When new compiler releases are created, currently we have to manually trigger publication with a separate empty commit. This is because GitHub prevents push events in a workflow from automatically triggering other workflows to prevent recursive runs.
Instead, manually call the standard build CI workflow so that a new compiler release is immediately published.
Unfortunately there's no way to test this before a release is actually created.

When a new release is created, trigger an immediate build and publish

---

.github/workflows/release.yml

Followup to #258
The release job failed with the following error:
```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/closure-compiler-npm/closure-compiler-npm/.github/workflows/build.yml'.
```
Updates the syntax slightly to work around this. Won't be testable until the next release though.

Modify workflow call syntax

---

build-scripts/build_compiler.js

Update the build target name for Bazel to reflect changes from https://github.com/google/closure-compiler/pull/3935

Update the build target name

---

.github/workflows/build.yml

While the trigger is listed as `workflow_call`, apparently the inherited event retains the original `workflow_dispatch` name. See https://github.com/github/docs/issues/16515
Hopefully fixes the release workflow to automatically publish to NPM.

Switch the event name allowed to publish to `workflow_dispatch`

---

packages/google-closure-compiler/README.md

I made this change in response to https://github.com/google/closure-compiler/discussions/4003

Update confusing statement about JS-native version

---

.github/workflows/build.yml

Several changes are recommended by GitHub. See output at the bottom of https://github.com/google/closure-compiler-npm/actions/runs/3422804900

Update build action to address warnings

---

build-scripts/graal.js

Fixes #272 
See https://www.graalvm.org/22.0/reference-manual/native-image/StaticImages/

Support multiple libc versions by dynamically linking against libc

---

build-scripts/build_compiler.js

Avoids utilizing the git tag which is failing to build the correct version during a release.

Utilize the package version for the compiler build

---

.github/workflows/build.yml

Allows a wider range of GLIBC versions. Fixes #280.

Switch the linux graal build runner for better GLIBC compatibility

---

build-scripts/graal.js

Reverts google/closure-compiler-npm#273
Compatibility for GLIBC was addressed in #280 so we can now go back to static linking.

Revert "Support multiple libc versions by dynamically linking against libc"

---

.github/workflows/build.yml
.github/workflows/release.yml
deployments.md

Since GitHub actions use the same commit as part of any re-used workflow, the new compiler version is not getting published. Require the Build CI action to be manually run after the release commit is created.

Manually run the Build CI as part of the release

---

.github/workflows/build.yml

Minor version update. Graal release notes indicate that the underlying JDK has security fixes.

Update Graal to 22.3.2

---

.github/workflows/build.yml

Now that the uber-jars are fixed, we should be able to turn these back on.

Turn nightly builds back on

---

build-scripts/graal.js

Broken due to NodeJS breaking change for security.
Fixes #306

Fix windows builds

---

.github/workflows/build.yml

This is a LSC run by http://go/ghss to upgrade all depreacated ubuntu-20.04 runners to ubuntu-24.04.
On April 1, 2025, GitHub will stop supporting ubuntu-20.04 runners and workflows configured with this label will cease to run.  This PR is an attempt to save you work by doing the upgrade for you.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it and deal with the problem yourselves.
More context and feedback: http://b/406537467

Update runners to ubuntu-24.04 from deprecated ubuntu-20.04 label

---

packages/google-closure-compiler/lib/gulp/index.js

Remove deprecated gulp usage and utilize modern error extension with causes.

Update gulp plugin to use modern logging and errors

---

build-scripts/reflection-config.json

Conformance configurations trigger runtime exceptions due to missing methods and fields
Fixes #316

Add reflection protection for GRAAL to prevent runtime exceptions

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/release.yml

Guards against the tag pointer being moved to include malicious code

Pin all GitHub actions to specific commit hashes

---

.github/workflows/build.yml
build-scripts/graal.js

Avoids including hundreds of MBs of javadoc in the native image binaries
This was diagnosed by using the latest version of GraalVM and using the `-H:+GenerateEmbeddedResourcesFile` flag.

Use more specific patterns for matching included resources
