google/closure-compiler-npm

README.md, lib/gulp/index.js, test/gulp.js
addresses #3
feel free to bikeshed on the option name :)
=> add option to skip compilation if no files in gulp stream

lib/gulp/index.js, lib/node/closure-compiler.js, test/node.js
I believe all of these references are undocumented and mainly for internal use.
=> Update variable naming to closer align with Google coding style

lib/gulp/index.js
Hopefully this fixes the nagging issues with #9.
=> Use the node streaming API to pipe input into stdin of the compiler

.travis.yml
Make sure travis doesn't cut a new release and merge the branch on a PR build.
=> Prevent releases on PR builds

README.md, lib/grunt/index.js, lib/gulp/index.js, lib/node/closure-compiler.js, test/node.js
=> Add the capability to provide arbitrary arguments to the java process.

test/compiler.js
This would fail if, for instance, the person doing the release did a
'git pull' instead of 'git checkout v20160713'
=> Add a test that the compiler submodule is synced to the right commit

package.json
=> Add minimum node version

test/fixtures/one.js, test/fixtures/two.js
I think this will satisfy all the requirements to make this a Google repo.
I'm going to start that process next.
=> Add license comment to test source files.

lib/gulp/index.js, lib/gulp/json-to-vinyl.js, test/gulp.js
Reverts #5 as the author declined to sign the Google CLA.
=> Remove contribution

.travis.yml, package.json
Updates package.json and travis settings
=> Update package settings to reflect ownership transfer

README.md
This simply updates the readme to correctly document the JS callback bindings.
=> Update the run signature for the jsCompiler node bindings

package.json, test/gulp.js, yarn.lock
The compiler now outputs a $week$.js file which interferes with tests. Exclude that file from tests.
=> Adjust tests to account for the new $weak$.js output from the compiler.

README.md
Hey, I corrected a typo in the `README`.
=> Typo: "it´s" -> "its"

build-scripts/graal-env.js, build-scripts/graal.js, build-scripts/reflection-config.json
Updates to Graal 19.0.0 which is the first full stable release.
Closes #134
=> Update to stable release of graal

.travis.yml, packages/google-closure-compiler/package.json
Also clean up the travis config
=> Attempt to fix the tests on the main repo which fail trying to run mocha

packages/google-closure-compiler/lib/node/closure-compiler-js.js, packages/google-closure-compiler/lib/node/closure-compiler.js
=> Update contrib paths to be based off the main package

packages/google-closure-compiler/lib/grunt/index.js
Add additional error information for Grunt plugin
=> Fix google/closure-compiler-npm/issues/169

packages/google-closure-compiler/README.md
Simply adding another reference to the windows native binary.
=> Minor tweak to readme to reference Windows

build-scripts/graal-env.js
Update to the latest Graal release: https://www.graalvm.org/release-notes/20_2/#2020
=> Update graal version to 20.2.0

packages/google-closure-compiler/lib/gulp/index.js
Fix Gulp error occurred during compiler
=> Fix google/closure-compiler-npm/issues/195

.github/workflows/build.yml, build-scripts/graal-env.js
=> Upgrade to the latest stable Graal version

packages/google-closure-compiler-osx/package.json
=> Add arm64 support for google-closure-compiler-osx

.github/workflows/build.yml
This is going to be the windows-latest default, see
https://github.com/actions/virtual-environments/issues/4856.
=> Update workflow to use Windows Server 2022.

.github/workflows/build.yml
Followup to #232 
Use upx to compress the macos binary
=> Add upx compression for MacOS binaries

yarn.lock
Updates lerna to the latest 3.x version.
=> Update lerna version

yarn.lock
Reverts google/closure-compiler-npm#239
Nightly build failed to publish after the update.
=> Revert "Update lerna version"

build-scripts/publish.js
In #241, I missed configuring the .npmrc file to allow for publication. The nightly job publication failed. This should fix the issue.
=> Setup npmrc to allow publication from github actions

.github/workflows/release.yml
Add git name and email in release workflow
=> Configure git to support creating a commit

package.json, packages/google-closure-compiler/package.json, yarn.lock
Update dependencies with known vulnerabilities
=> Update dependencies to address security alerts

package.json, yarn.lock
=> Update deps to address dependabot alerts

build-scripts/build_compiler.js
This will hopefully fix the currently-broken CI build.
=> Correct the name of the uber deploy jar

yarn.lock
Minor dep update to address dependabot warning.
=> Update dependency to address security warning

.github/workflows/build.yml
Updates to the newest GRAAL release
=> Update GRAAL to the 22.3.0 release

package.json, yarn.lock
Addresses the low finding for debug which is only utilized for tests/builds.
=> Update dependencies to address security finding

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/release.yml, build-scripts/graal.js
Use the latest versions of actions and update java and node versions.
=> Update github actions versions

packages/google-closure-compiler/lib/node/index.js, packages/google-closure-compiler/test/node.js, test/compiler.js
Suppresses error messages reported in https://github.com/google/closure-compiler/issues/4229
=> Suppress Sun unsafe memory warnings on JDK 24
